-- Migration: create_products
-- Created at: 2026-07-02 00:00:00

-- 1. Membuat tabel products
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price text NOT NULL,
  original_price text,
  category text NOT NULL,
  image_url text NOT NULL,
  images_array text[] NOT NULL,
  tag text,
  description text NOT NULL,
  long_description text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Mengaktifkan Row Level Security (opsional tapi disarankan)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Membuat kebijakan agar siapa saja bisa membaca data produk (Public Read Access)
CREATE POLICY "Enable read access for all users" ON public.products
  FOR SELECT USING (true);

-- 4. Mengisi data awal (Dummy Data dari Frontend sebelumnya)
INSERT INTO public.products (name, price, original_price, category, image_url, images_array, tag, description, long_description)
VALUES
  (
    'Kiokilho Classic Tote', 
    'Rp 499.000', 
    'Rp 799.000', 
    'Tote Bag', 
    '/src/assets/tote_bag.png', 
    ARRAY['/src/assets/tote_bag.png', '/src/assets/sling_bag.png', '/src/assets/backpack_bag.png'], 
    'Best Seller', 
    'Mahakarya tote bag ikonik dengan ruang penyimpanan luas. Dirajut dari serat goni pilihan dan sentuhan kain jumputan yang memancarkan pesona klasik nan elegan.', 
    'Diciptakan untuk Anda yang menghargai keindahan dalam kesederhanaan. Kiokilho Classic Tote dibuat secara manual oleh pengrajin lokal berbakat yang mendedikasikan lebih dari 72 jam pengerjaan untuk setiap tasnya. Serat goni premium yang digunakan tidak hanya ramah lingkungan, tetapi juga memiliki durabilitas tinggi untuk pemakaian bertahun-tahun. Lapisan dalam menggunakan katun organik yang lembut, memastikan barang-barang berharga Anda tetap aman dari goresan.'
  ),
  (
    'Urban Sling', 
    'Rp 349.000', 
    'Rp 599.000', 
    'Sling Bag', 
    '/src/assets/sling_bag.png', 
    ARRAY['/src/assets/sling_bag.png', '/src/assets/backpack_bag.png', '/src/assets/tote_bag.png'], 
    'New Arrival', 
    'Ringkas, dinamis, dan modis. Tas selempang yang dirancang untuk menemani gaya hidup urban Anda tanpa mengorbankan nilai estetika nusantara.', 
    'Mobilitas tinggi menuntut kepraktisan tanpa mengorbankan gaya. Urban Sling hadir dengan desain asimetris yang ergonomis, memeluk tubuh Anda dengan sempurna saat berjalan melintasi hiruk pikuk kota. Dilengkapi dengan kompartemen tersembunyi yang tahan air untuk mengamankan gawai Anda. Aksen jumputan pada tali selempang menjadi statement piece yang membedakan Anda dari keramaian.'
  ),
  (
    'Explorer Pack', 
    'Rp 899.000', 
    'Rp 1.299.000', 
    'Backpack', 
    '/src/assets/backpack_bag.png', 
    ARRAY['/src/assets/backpack_bag.png', '/src/assets/tote_bag.png', '/src/assets/sling_bag.png'], 
    NULL, 
    'Ransel premium yang tangguh namun tetap elegan. Menggabungkan material goni berdaya tahan tinggi dengan ornamen kulit & kuningan asli untuk petualangan yang penuh gaya.', 
    'Sang pendamping setia untuk jiwa-jiwa petualang. Explorer Pack mendefinisikan ulang arti ransel alam dengan sentuhan luxury. Panel belakangnya dilengkapi bantalan ergonomis berongga untuk sirkulasi udara maksimal. Gesper kuningan solid yang dibuat khusus memastikan ransel tertutup rapat. Ruang utamanya yang luas siap menampung laptop 15 inci beserta esensial perjalanan Anda selama akhir pekan.'
  );
